spring.application.name=InsightData
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=
gemini.api.key=AIzaSyDbOfOdMBU04IweUB0tDgcPdpd6kGvzTn4
server.port=${PORT:8080}